# Generated by Django 3.2.9 on 2021-11-19 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=150, verbose_name='Пользователь')),
                ('cryptocurrency', models.CharField(max_length=150, verbose_name='Криптовалюта')),
                ('cryptocurrency_symbol', models.CharField(max_length=150, verbose_name='символ')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='цена')),
            ],
            options={
                'verbose_name': 'Клиенты',
                'verbose_name_plural': 'Клиент',
            },
        ),
    ]
